USE ERP_Quality;

CREATE TABLE IF NOT EXISTS Complaint (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    DocNo VARCHAR(50) NOT NULL UNIQUE,
    CustomerName VARCHAR(100) NOT NULL,
    ComplaintType VARCHAR(100) NOT NULL,
    Severity VARCHAR(50) NOT NULL,
    ItemCode VARCHAR(50) NOT NULL,
    ItemName VARCHAR(100),
    BatchNo VARCHAR(50),
    ProductionOrderNo VARCHAR(50),
    InvoiceNo VARCHAR(50),
    QtySupplied INT,
    QtyComplained INT,
    Description TEXT,
    LoggedOn DATE,
    LoggedBy VARCHAR(100),
    Owner VARCHAR(100),
    DueOn DATE,
    Status VARCHAR(50) DEFAULT 'LOGGED',
    Resolution VARCHAR(50) DEFAULT 'PENDING',
    ResolutionValue DECIMAL(10,2),
    RootCause TEXT,
    CauseCategory VARCHAR(50),
    NcrDocNo VARCHAR(50),
    CapaDocNo VARCHAR(50),
    ClosedOn DATE,
    Remarks TEXT,
    Version INT DEFAULT 1,
    DeletedAt DATETIME,
    CreatedBy VARCHAR(100),
    CreatedDate DATETIME,
    ModifiedBy VARCHAR(100),
    ModifiedDate DATETIME
);
