USE ERP_Quality;

CREATE TABLE IF NOT EXISTS QualitySeverity (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) UNIQUE NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS QualityCause (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) UNIQUE NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE
);

INSERT IGNORE INTO QualitySeverity (Name) VALUES 
('CRITICAL'), ('MAJOR'), ('MINOR');

INSERT IGNORE INTO QualityCause (Name) VALUES 
('MAN'), ('MACHINE'), ('MATERIAL'), ('METHOD'), ('MEASUREMENT'), ('ENVIRONMENT');
