"""initial organisation + iam + core tables

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-10

The initial migration builds the schema straight from the SQLAlchemy metadata,
so the DDL always matches the models exactly. Subsequent migrations are
autogenerated with `alembic revision --autogenerate` and reviewed by hand
(CLAUDE.md §6, §9.6). Both upgrade and downgrade are exercised in CI
(migration up/down test).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from app.models import Base

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
