"""Add mst_cost_centre

Revision ID: 76e464ebba37
Revises: 0009_stock_count
Create Date: 2026-08-25 18:46:06.461000
"""
from __future__ import annotations

from collections.abc import Sequence

# pyrefly: ignore [missing-import]
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '76e464ebba37'
down_revision: str | None = '0009_stock_count'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mst_cost_centre',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('parent_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('cost_centre_type', sa.String(length=30), nullable=False),
    sa.Column('owner_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('plant_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('department_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('level', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('is_postable', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('branch_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=26), nullable=False),
    sa.Column('version', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_by', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('deleted_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('deleted_key', mysql.DATETIME(fsp=6), sa.Computed("IFNULL(deleted_at, '1970-01-01 00:00:00')", persisted=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', 'deleted_key', name='uk_cc_code'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_mst_cost_centre_branch_id'), 'mst_cost_centre', ['branch_id'], unique=False)
    op.create_index(op.f('ix_mst_cost_centre_company_id'), 'mst_cost_centre', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mst_cost_centre_company_id'), table_name='mst_cost_centre')
    op.drop_index(op.f('ix_mst_cost_centre_branch_id'), table_name='mst_cost_centre')
    op.drop_table('mst_cost_centre')
    # ### end Alembic commands ###
